PnP implementation
Azure/azure-iot-sdk-c pull request #2010
Opened 2021-06-25 22:03 UTC by jspaith

Adds implementation of PnP, specifically properties parsing, the wrappers for twin|events, and the SUBSCRIBE to command logic in the core which is a bit tricker.

Leaving out the convenience layer for now.  It's implemented, but never been tested either via UT or even E2E (as samples use LL).

Note the original plan had been to bring in the multi-component sample at this point, but instead bringing in proudct code to get us sooner to "usable code".  That - along with the UT which are actively being written - on future checkin.

2021-06-26 00:13 UTC, danewalton requested changes

2021-06-26 00:13 UTC, danewalton commented on iothub_client/src/iothub_client_properties.c
> +// tell a property from a sub-component, as the protocol does not guaranteed we will received a "__t" marker over the network
```suggestion
// tell a property from a sub-component, as the protocol does not guarantee we will receive a "__t" marker over the network
```

2021-06-26 00:13 UTC, danewalton commented on iothub_client/src/iothub_client_properties.c
> +            success =  (i == numComponentsInModel);
```suggestion
            success = (i == numComponentsInModel);
```

2021-06-26 00:13 UTC, danewalton commented on iothub_client/src/iothub_client_properties.c
> +
nit: empty line

2021-06-26 00:13 UTC, danewalton commented on iothub_client/src/iothub_client_properties.c
> +        // because if this fails we waint to fail creation of the enumerator.  A twin without version info
```suggestion
        // because if this fails we want to fail creation of the enumerator.  A twin without version info
```

2021-06-28 17:28 UTC, jspaith reviewed
As always many thanks @danewalton for your eagle eyes.  Fixed up stuff in latest commit.

2021-06-28 17:28 UTC, jspaith commented on iothub_client/src/iothub_client_properties.c
> +        // because if this fails we waint to fail creation of the enumerator.  A twin without version info
fixed.

2021-06-28 17:53 UTC, danewalton approved these changes

2021-06-28 17:53 UTC, danewalton commented on iothub_client/src/iothub_client_properties.c
> +    COMPONENT_PARSE_SUB_STATE_COMPONENT,
```suggestion
    COMPONENT_PARSE_STATE_SUB_COMPONENT,
```

2021-07-02 00:14 UTC, jspaith commented on iothub_client/src/iothub_client_properties.c
> +    COMPONENT_PARSE_SUB_STATE_COMPONENT,
FIxing...

2021-07-02 00:17 UTC, merged