Bump submodule | Compile on Ubuntu 22.04
Azure/azure-iot-sdk-c pull request #2346
Opened 2022-08-04 19:44 UTC by danewalton

- Bumps submodule to compile with OpenSSL 3.0
- Adds successful gate check for Ubuntu 22.04

2022-08-05 17:45 UTC, ericwol-msft commented on build/.vsts-ci.yml
> +  - container: linux-c-ubuntu-2204
blocking until LTS release

2022-08-05 17:45 UTC, ericwol-msft requested changes
blocking until LTS release

2022-08-09 23:50 UTC, ericwol-msft approved these changes

2022-08-15 15:01 UTC, danewalton commented
/azp run C-canary

2022-08-17 18:29 UTC, ericwol-msft approved these changes

2022-08-23 19:31 UTC, danewalton commented
/azp run C-canary

2022-08-23 21:07 UTC, danewalton commented
/azp run C-canary

2022-08-24 17:06 UTC, danewalton commented
/azp run C-canary

2022-08-24 19:52 UTC, danewalton commented
/azp run C-canary

2022-08-31 22:47 UTC, ewertons approved these changes

2022-09-01 02:05 UTC, merged